Processed review comments
Signed-off-by: Bart Poot <bart.poot@adlinktech.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -37,53 +37,57 @@ submit_to_coverity_scan: &submit_to_coverity_scan
                "https://scan.coverity.com/builds";
   fi
 
-freertos: &freertos
-  if [ "${FREERTOS}" = "true" ]; then
-    cd ports/freertos-posix;
-    git clone https://github.com/shlinym/FreeRTOS-Sim.git;
-    mkdir build;
-    cd build;
-    cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..;
-    cmake --build . --target install;
-    cd ../../..;
-    if [ "${LWIP}" = "true" ]; then
-      WITH_LWIP=on
-      cd ports/freertos-posix/lwip;
-      git clone https://git.savannah.nongnu.org/git/lwip.git;
-      cd lwip;
-      git checkout tags/STABLE-2_1_2_RELEASE -b STABLE-2_1_2_RELEASE;
-      cd ..;
-      git clone https://git.savannah.nongnu.org/git/lwip/lwip-contrib.git;
-      cd lwip-contrib;
-      git checkout tags/STABLE-2_1_0_RELEASE -b STABLE-2_1_0_RELEASE;
-      cd ..;
-      mkdir lwip-contrib/ports/unix/example_app/build;
-      cd lwip-contrib/ports/unix/example_app/build;
-      cmake ..;
-      cp ../../../../../lwipcfg.h ../../../../examples/example_app;
-      cmake --build . --target all;
-      cd ../../../../../..;
-      mkdir -p build;
-      cd build;
-      cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..;
-      cmake --build . --target install;
-      cd ../../..;
+build_simulator: &build_simulator
+  - cd "${TRAVIS_BUILD_DIR}/ports/freertos-posix"
+  - git clone -b "v9.0.0" --single-branch https://github.com/shlinym/FreeRTOS-Sim.git FreeRTOS-Sim
+  - rm -rf build
+  - mkdir build
+  - cd build
+  - cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
+  - cmake --build . --target install
+
+build_lwip: &build_lwip
+  - cd "${TRAVIS_BUILD_DIR}/ports/freertos-posix/lwip"
+  - rm -rf lwip
+  - git clone -b STABLE-2_1_2_RELEASE --single-branch https://git.savannah.nongnu.org/git/lwip.git lwip
+  - rm -rf lwip-contrib
+  - git clone -b STABLE-2_1_0_RELEASE --single-branch https://git.savannah.nongnu.org/git/lwip/lwip-contrib.git lwip-contrib
+  - mkdir ${TRAVIS_BUILD_DIR}/cyclonedds/ports/freertos-posix/lwip/lwip-contrib/ports/unix/example_app/build
+  - cd "${TRAVIS_BUILD_DIR}/cyclonedds/ports/freertos-posix/lwip/lwip-contrib/ports/unix/example_app/build"
+  - cmake .
+  - cp "${TRAVIS_BUILD_DIR}/ports/freertos-posix/lwip/lwipcfg.h" "${TRAVIS_BUILD_DIR}/ports/freertos-posix/lwip/lwip-contrib/ports/unix/example_app"
+  - cmake --build . --target lwipcontribportunix
+  - cmake --build . --target lwipcore
+  - cd "${TRAVIS_BUILD_DIR}/ports/freertos-posix"
+  - rm -rf build
+  - mkdir -p build
+  - cd build
+  - cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/install ..
+  - cmake --build . --target install
+
+build_target: &build_target
+  - mkdir build
+  - cd build
+  - conan install -b missing -s arch=${ARCH} -s build_type=${BUILD_TYPE} ..
+  - if [ "${FREERTOS}" = "true" ]; then
+      cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
+            -DCMAKE_TOOLCHAIN_FILE=../ports/freertos-posix/toolchain.cmake
+            -DCMAKE_INSTALL_PREFIX=$(pwd)/install
+            -DUSE_SANITIZER=${ASAN}
+            -DENABLE_SSL=${SSL}
+            -DBUILD_TESTING=on
+            -DWITH_FREERTOS=on
+            -DWITH_LWIP=${LWIP}
+            -G "${GENERATOR}" .. || true;
     else
-      WITH_LWIP=off;
-    fi;
-    mkdir build;
-    cd build;
-    conan install -b missing -s arch=${ARCH} -s build_type=${BUILD_TYPE} ..;
-    cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-          -DCMAKE_TOOLCHAIN_FILE=../ports/freertos-posix/toolchain.cmake
-          -DCMAKE_INSTALL_PREFIX=$(pwd)/install
-          -DUSE_SANITIZER=${ASAN}
-          -DENABLE_SSL=${SSL}
-          -DBUILD_TESTING=on
-          -DWITH_FREERTOS=on
-          -DWITH_LWIP=${WITH_LWIP}
-          -G "${GENERATOR}" .. || true;
-    case "${GENERATOR}" in
+      cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
+            -DCMAKE_INSTALL_PREFIX=$(pwd)/install
+            -DUSE_SANITIZER=${ASAN}
+            -DENABLE_SSL=${SSL}
+            -DBUILD_TESTING=on
+            -G "${GENERATOR}" ..;
+    fi
+  - case "${GENERATOR}" in
       "Unix Makefiles")
         ${SCAN_BUILD} cmake --build . --config ${BUILD_TYPE} --target install -- -j 4
         ;;
@@ -94,8 +98,55 @@ freertos: &freertos
         ${SCAN_BUILD} cmake --build . --config ${BUILD_TYPE} --target install
         ;;
     esac;
-    CYCLONEDDS_URI='<CycloneDDS><Domain><General><NetworkInterfaceAddress>lo0</NetworkInterfaceAddress></General><Internal><EnableExpensiveChecks>all</EnableExpensiveChecks></Internal><Tracing><Verbosity>finest</Verbosity><OutputFile>lite.log</OutputFile></Tracing></Domain></CycloneDDS>' ctest -j 1 --output-on-failure -T test -R "ddsrt_atomics|ddsrt_environ|ddsrt_heap|ddsrt_getifaddrs|ddsrt_sync|ddsrt_strtoll|ddsrt_thread|ddsrt_strcasecmp|ddsrt_strncasecmp|dds_log|ddsrt_random|ddsrt_strlcpy|ddsrt_strlcat|ddsrt_sockaddrfromstr|ddsrt_sockaddrtostr|ddsrt_sockets|ddsrt_gethostbyname|ddsrt_select|ddsrt_listener|ddsc_qos|ddsc_listener|ddsc_participant_lookup_none|ddsc_publisher_coherency" -E "ddsc_listener_propagation|ddsc_listener_matched|ddsc_listener_publication_matched|ddsc_listener_subscription_matched|ddsc_listener_incompatible_qos|ddsc_listener_data_available|ddsc_listener_data_available_delete_writer|ddsc_listener_data_available_delete_writer_disposed|ddsc_listener_data_on_readers|ddsc_listener_sample_lost|ddsc_listener_sample_rejected|ddsc_listener_liveliness_changed" -C ${BUILD_TYPE};
+
+# Notes on test settings:
+# - CYCLONEDDS_URI:
+#   - EnableExpensiveChecks: for the few horrendously expensive (but pretty thorough)
+#     integrity checks, in particular on the WHC and the RHC, but there may be more
+#   - config to stderr: gives the configuration used when running the test in conjunction
+#     with "--output-on-failure" (sadly that still doesn't output the failed
+#     assertions ...)
+# - -j 4: run 4 tests in parallel, this saves quite a bit of time because the VMs are
+#   all dual-core
+# - --output-on-failed: print whatever output the test generated when it failed, which
+#   can obviously be quite helpful for debugging
+# - -E ...: regex of tests to exclude:
+#     CUnit_ddsrt_random_default_random: performs a Chi-square test on the output of
+#     the random generator, but this does produce the odd failure (it should!).  The
+#     code has been vetted, the test has been run a great many times (with the odd
+#     failure), and so we now simply skip the test to avoid the spurious failures.
+run_ctest: &run_ctest
+  if [ "${FREERTOS}" = "true" ]; then
+    CYCLONEDDS_URI='<CycloneDDS><Domain><General><NetworkInterfaceAddress>lo0</NetworkInterfaceAddress></General><Internal><EnableExpensiveChecks>all</EnableExpensiveChecks></Internal><Tracing><Verbosity>finest</Verbosity><OutputFile>lite.log</OutputFile></Tracing></Domain></CycloneDDS>' ctest -j 1 --output-on-failure -T test -R "ddsrt_atomics|""ddsrt_environ|""ddsrt_heap|""ddsrt_getifaddrs|""ddsrt_sync|""ddsrt_strtoll|""ddsrt_thread|""ddsrt_strcasecmp|""ddsrt_strncasecmp|""dds_log|""ddsrt_random|""ddsrt_strlcpy|""ddsrt_strlcat|""ddsrt_sockaddrfromstr|ddsrt_sockaddrtostr|ddsrt_sockets|ddsrt_gethostbyname|ddsrt_select|ddsrt_listener|ddsc_qos|ddsc_listener|ddsc_participant_lookup_none|ddsc_publisher_coherency" -E "ddsc_listener_propagation|ddsc_listener_matched|ddsc_listener_publication_matched|ddsc_listener_subscription_matched|ddsc_listener_incompatible_qos|ddsc_listener_data_available|ddsc_listener_data_available_delete_writer|ddsc_listener_data_available_delete_writer_disposed|ddsc_listener_data_on_readers|ddsc_listener_sample_lost|ddsc_listener_sample_rejected|ddsc_listener_liveliness_changed" -C ${BUILD_TYPE};
+  else
+    CYCLONEDDS_URI='<CycloneDDS><Domain><Internal><EnableExpensiveChecks>all</EnableExpensiveChecks></Internal><Tracing><Verbosity>config</Verbosity><OutputFile>stderr</OutputFile></Tracing></Domain></CycloneDDS>' ctest -j 4 --output-on-failure -T test -E '^CUnit_ddsrt_random_default_random$' -C ${BUILD_TYPE};
   fi
+
+build_example: &build_example
+  - if [ "${ASAN}" != "none" ]; then
+      CMAKE_LINKER_FLAGS="-DCMAKE_LINKER_FLAGS=-fsanitize=${USE_SANITIZER}";
+      CMAKE_C_FLAGS="-DCMAKE_C_FLAGS=-fsanitize=${USE_SANITIZER}";
+    fi
+  - mkdir install/share/CycloneDDS/examples/helloworld/build
+  - cd install/share/CycloneDDS/examples/helloworld/build
+  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
+          ${CMAKE_C_FLAGS}
+          ${CMAKE_LINKER_FLAGS}
+          -G "${GENERATOR}" ..
+  - cmake --build . --config ${BUILD_TYPE}
+
+build_the_target: &build_the_target
+  - if [ "${FREERTOS}" = "true" ]; then
+      *build_simulator;
+      if [ "${LWIP}" = "true" ]; then
+        *build_lwip;
+      fi;
+    fi
+  - *build_target
+  - *run_ctest
+  - if [ "${FREERTOS}" != "true" ]; then
+      *build_example;
+    fi
 
 linux_gcc: &linux_gcc
   os: linux
@@ -253,63 +304,21 @@ before_script:
   - conan profile new default --detect
   - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
 
-# Notes on test settings:
-# - CYCLONEDDS_URI:
-#   - EnableExpensiveChecks: for the few horrendously expensive (but pretty thorough)
-#     integrity checks, in particular on the WHC and the RHC, but there may be more
-#   - config to stderr: gives the configuration used when running the test in conjunction
-#     with "--output-on-failure" (sadly that still doesn't output the failed
-#     assertions ...)
-# - -j 4: run 4 tests in parallel, this saves quite a bit of time because the VMs are
-#   all dual-core
-# - --output-on-failed: print whatever output the test generated when it failed, which
-#   can obviously be quite helpful for debugging
-# - -E ...: regex of tests to exclude:
-#     CUnit_ddsrt_random_default_random: performs a Chi-square test on the output of
-#     the random generator, but this does produce the odd failure (it should!).  The
-#     code has been vetted, the test has been run a great many times (with the odd
-#     failure), and so we now simply skip the test to avoid the spurious failures.
 script:
-  - *freertos
   - if [ "${FREERTOS}" = "true" ]; then
-      :;
-    else
-      mkdir build;
-      cd build;
-      conan install -b missing -s arch=${ARCH} -s build_type=${BUILD_TYPE} ..;
-      cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-            -DCMAKE_INSTALL_PREFIX=$(pwd)/install
-            -DUSE_SANITIZER=${ASAN}
-            -DENABLE_SSL=${SSL}
-            -DBUILD_TESTING=on
-            -DWERROR=on
-            -G "${GENERATOR}" ..;
-      case "${GENERATOR}" in
-        "Unix Makefiles")
-          ${SCAN_BUILD} cmake --build . --config ${BUILD_TYPE} --target install -- -j 4
-          ;;
-        "Visual Studio "*)
-          ${SCAN_BUILD} cmake --build . --config ${BUILD_TYPE} --target install -- -nologo -verbosity:minimal -maxcpucount -p:CL_MPCount=2
-          ;;
-        *)
-          ${SCAN_BUILD} cmake --build . --config ${BUILD_TYPE} --target install
-          ;;
-      esac;
-      CYCLONEDDS_URI='<CycloneDDS><Domain><Internal><EnableExpensiveChecks>all</EnableExpensiveChecks></Internal><Tracing><Verbosity>config</Verbosity><OutputFile>stderr</OutputFile></Tracing></Domain></CycloneDDS>' ctest -j 4 --output-on-failure -T test -E '^CUnit_ddsrt_random_default_random$' -C ${BUILD_TYPE};
-      if [ "${ASAN}" != "none" ]; then
-        CMAKE_LINKER_FLAGS="-DCMAKE_LINKER_FLAGS=-fsanitize=${USE_SANITIZER}";
-        CMAKE_C_FLAGS="-DCMAKE_C_FLAGS=-fsanitize=${USE_SANITIZER}";
+      if [ "${LWIP}" = "true" ]; then
+        ./scripts/build_the_target freertos lwip "${RM}";
+      else
+        ./scripts/build_the_target freertos "${RM}";
       fi;
-      mkdir install/share/CycloneDDS/examples/helloworld/build;
-      cd install/share/CycloneDDS/examples/helloworld/build;
-      cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-            ${CMAKE_C_FLAGS}
-            ${CMAKE_LINKER_FLAGS}
-            -G "${GENERATOR}" ..;
-      cmake --build . --config ${BUILD_TYPE};
-      cd "${TRAVIS_BUILD_DIR}/build";
+    else
+      if [ "${LWIP}" = "true" ]; then
+        ./scripts/build_the_target lwip "${RM}";
+      else
+        ./scripts/build_the_target "${RM}";
+      fi;
     fi
+  - cd "${TRAVIS_BUILD_DIR}/build"
 
 after_success:
   - *submit_to_coverity_scan
-
